[package]
name = "wget"
version = "0.1.0"
authors = ["Lukasz <lukasz.wawrzyk@gmail.com>"]

[dependencies]
time = "0.1.35"
getopts = "0.2.14"
rpassword = "0.2.2"
regex = "0.1.69"
hyper = "0.9.5"

[dependencies.url]
git = "https://github.com/servo/rust-url"
